# -*- coding: utf-8 -*-
"""Assignment-1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lMfDrToRO4DCjTgb6M1O_VOnqDG6wiio
"""

import numpy as np
import matplotlib.pyplot as plt
from scipy.stats import bernoulli

test=int(1e6)
sample_size = 1000  # No of students in a school
event_size1 = 430   # No of girls in a school
event_size2 = ((10*event_size1)/(100))    # No of girls in class XII


prob_1 = event_size1/sample_size   # event 1 = prob. that a chosen student is a girl
prob_2 = event_size2/sample_size   # event 2 = prob. that a chosen student is a girl from Class XII among all students  
the_prob=prob_2/prob_1     # event 3 = prob. that a student chosen randomly studies in Class XII given that it is girl 

#Simulating using Bernoulli r.v.s for 10000000 trials such that event 1-chosen student is a girl and event 2-chosen student is a girl from class XII with probablity p
data_event_1 = bernoulli.rvs(size=test,p=prob_1)
data_event_2 = bernoulli.rvs(size=test,p=prob_2)

#Calculating the number of favourable outcomes in both events where 1 is taken as a girl  
err_ind1 = np.nonzero(data_event_1 == 1)  
err_ind2 = np.nonzero(data_event_2 == 1) 
 
#calculating the probability for event 1
e_n1 = np.size(err_ind1)/test

#Calculating the probability for event 2
e_n2 = np.size(err_ind2)/test

#Calculating the probability for event 2 given that event 1 has occured
final_prob = e_n2/e_n1

print("According to simulation, Probability for Event 3 : ",final)
print("Theoretically Calculated Probability for Event 3 : ",the_prob )